runtime: python311
env: standard
instance_class: F1
handlers:
  - url: /.*
    script: auto
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
service_account: bplrankings@appspot.gserviceaccount.com

